name: TheTOwOwer
version: 1.0.0
author: FloLeProto
main: com.floleproto.thetower.Main
api-version: 1.18

commands:
  host:
    description: Send a message for all
  start:
    description: Start the countdown
  cancelstart:
    description: Stop the countdown
  save:
    description: Save the inventory (edit mode only)
  rules:
    description: Print the rules in the chat
  savechest:
    description: Save chests